# Generated by Django 5.1.11 on 2025-06-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingreport',
            name='school',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='feedingreport',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
