# Generated by Django 5.1.11 on 2025-07-07 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='Assign a school to this user (for school admins)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school'),
        ),
    ]
