# Generated by Django 5.1.11 on 2025-07-09 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_manualmpesadonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualmpesadonation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
