# Generated by Django 5.1.11 on 2025-07-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
